-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- DELETE from users where 1=1;
-- INSERT INTO users (user_id, name) VALUES
--   ('auth0|61a5c43193d5400069c8d6f8', 'john');
