-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO limits (id, name) VALUES
--   (1, '.25/50'),
--   (2, '50/1'),
--   (3, '1/2'),
--   (4, '3/5'),
--   (5, '5/10');
